# -*- coding: utf-8 -*-
"""AI Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Racm2oG1NM5TnhEhOmqsOl8nIQ--yXLm

# Installing Groq
"""

!pip install groq requests -q

"""# Setting Groq API"""

GROQ_API_KEY = "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"

"""# Initialize Groq Client and Response Generation Function"""

from groq import Groq

client = Groq(api_key=GROQ_API_KEY)

def generate(prompt, system="You are a helpful medical assistant."):
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": system},
            {"role": "user",   "content": prompt}
        ],
        max_tokens=1024
    )
    return response.choices[0].message.content

# Test it
print(generate("Say hello in one sentence"))

"""# Language Detection for English, Urdu, and Roman Urdu Input"""

def detect_language(text):
    # Check for Urdu script characters
    for char in text:
        if '\u0600' <= char <= '\u06FF':
            return "URDU"

    # Check for Roman Urdu common words
    roman_urdu_words = [
        "mjy", "mujhe", "karo", "batao", "hai", "hain", "ky", "ka",
        "ki", "ko", "mn", "mein", "ap", "aap", "kya", "nahi", "aur",
        "krny", "karna", "wala", "hua", "thi", "tha", "hoga"
    ]
    text_lower = text.lower()
    for word in roman_urdu_words:
        if word in text_lower.split():
            return "URDU"

    return "ENGLISH"

"""# Task Classification for Medical Queries"""

def classify_task(text):
    text_lower = text.lower()

    # Lab test keywords
    lab_keywords = [
        "hba1c", "hemoglobin", "wbc", "rbc", "glucose", "cholesterol",
        "test", "result", "level", "mg", "g/dl", "mmol", "%",
        "blood", "urine", "report", "value", "normal", "abnormal",
        "khoon", "sugar", "test", "nتیجہ"
    ]

    # Terminology keywords
    term_keywords = [
        "what is", "what does", "meaning", "define", "explain",
        "diagnosed with", "prescribed", "syndrome", "disorder",
        "kya hai", "matlab", "batao", "samjhao", "کیا ہے", "مطلب"
    ]

    # Literature/research keywords
    lit_keywords = [
        "research", "study", "studies", "evidence", "pubmed",
        "treatment", "therapy", "effective", "cure", "latest",
        "tareeqa", "ilaj", "طریقہ", "علاج", "stress", "anxiety"
    ]

    for word in lab_keywords:
        if word in text_lower:
            return "LAB_TEST"

    for word in term_keywords:
        if word in text_lower:
            return "TERMINOLOGY"

    for word in lit_keywords:
        if word in text_lower:
            return "LITERATURE"

    return "TERMINOLOGY"  # default fallback

"""# Medical Query Handlers: Lab Tests, Terminology, and Literature Responses"""

def lab_test_interpreter(user_input, language):
    if language == "URDU":
        system = "آپ ایک طبی معاون ہیں۔ خون کے ٹیسٹ کی قدریں سادہ اردو میں سمجھائیں۔"
        prompt = f"یہ میرے ٹیسٹ کے نتائج ہیں:\n{user_input}\nہر قدر کو سمجھائیں کہ نارمل ہے یا نہیں اور کیا کرنا چاہیے۔"
    else:
        system = "You are a medical assistant. Explain lab results in simple, clear English for patients."
        prompt = f"""Analyze these lab test values:
{user_input}

For each value:
1. State if NORMAL ✅ or ABNORMAL ⚠️
2. Give the normal range
3. Explain what it means simply
4. Give one practical suggestion

End with a short summary."""

    return generate(prompt, system)


def terminology_explainer(user_input, language):
    if language == "URDU":
        system = "آپ ایک طبی معاون ہیں۔ مشکل طبی الفاظ سادہ اردو میں سمجھائیں۔"
        prompt = f"یہ طبی الفاظ یا جملہ سمجھائیں:\n{user_input}"
    else:
        system = "You are a medical assistant. Explain medical terms in very simple English."
        prompt = f"""Explain the medical terms in this text:
{user_input}

For each medical term:
1. Give a simple everyday meaning
2. One sentence explanation

End with a plain English summary of the whole thing."""

    return generate(prompt, system)


def literature_analyzer(user_input, language):
    if language == "URDU":
        system = "آپ ایک طبی معاون ہیں۔ طبی سوالوں کے جواب سادہ اردو میں دیں۔"
        prompt = f"اس طبی موضوع پر معلومات دیں:\n{user_input}\nآسان الفاظ میں بتائیں۔"
    else:
        system = "You are a medical research assistant. Answer based on established medical knowledge."
        prompt = f"""Answer this medical question based on research:
{user_input}

Structure your answer as:
- Key Findings (3-4 bullet points)
- What This Means For You (simple explanation)
- Key Takeaways (numbered list)"""

    return generate(prompt, system)

"""# Medical Image Analysis using Groq Vision Model"""

import base64
from pathlib import Path

def encode_image(image_path):
    """Convert image to base64"""
    with open(image_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

def analyze_image(image_path, language, user_question=""):
    """Analyze any medical image or lab report photo"""

    # Check file exists
    if not Path(image_path).exists():
        return "❌ Image file not found. Please check the path."

    # Get file extension
    ext = Path(image_path).suffix.lower()
    mime_types = {
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".png": "image/png",
        ".webp": "image/webp"
    }
    mime_type = mime_types.get(ext, "image/jpeg")

    # Encode image
    image_data = encode_image(image_path)

    # Build prompt based on language
    if language == "URDU":
        if user_question:
            prompt = f"یہ میڈیکل تصویر دیکھیں اور اس سوال کا جواب اردو میں دیں: {user_question}"
        else:
            prompt = """یہ میڈیکل تصویر یا لیب رپورٹ دیکھیں اور اردو میں بتائیں:
1. یہ کس قسم کی تصویر یا رپورٹ ہے؟
2. اہم نتائج کیا ہیں؟
3. کوئی غیر معمولی چیز ہے تو بتائیں
4. مریض کو کیا کرنا چاہیے؟"""
    else:
        if user_question:
            prompt = f"Look at this medical image and answer: {user_question}"
        else:
            prompt = """Analyze this medical image or lab report and explain:
1. What type of image/report is this?
2. What are the key findings?
3. Are there any abnormal values or concerning findings? Flag them with ⚠️
4. What should the patient do next?

Keep the explanation simple and patient-friendly."""

    # Call Groq vision model
    try:
        response = client.chat.completions.create(
            model="meta-llama/llama-4-scout-17b-16e-instruct",  # Groq's vision model
            messages=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:{mime_type};base64,{image_data}"
                            }
                        },
                        {
                            "type": "text",
                            "text": prompt
                        }
                    ]
                }
            ],
            max_tokens=1024
        )
        return response.choices[0].message.content

    except Exception as e:
        return f"❌ Image analysis failed: {str(e)}"

"""# MedAssist Agent: Main Orchestration Pipeline"""

def medassist_agent(user_input):
    print("\n" + "="*60)
    print("🤖 MedAssist Agent Processing...")
    print("="*60)

    language = detect_language(user_input)
    print(f"🌐 Language detected: {language}")

    task = classify_task(user_input)
    print(f"📋 Task type: {task}")

    if task == "LAB_TEST":
        print("🔬 Running Lab Test Interpreter...")
        result = lab_test_interpreter(user_input, language)
    elif task == "TERMINOLOGY":
        print("📖 Running Terminology Explainer...")
        result = terminology_explainer(user_input, language)
    elif task == "LITERATURE":
        print("📚 Running Literature Analyzer...")
        result = literature_analyzer(user_input, language)

    print("\n📄 RESULT:\n")
    print(result)
    print("="*60)

    # Save to CSV
    save_log(user_input, language, task, result)

"""# MedAssist Chat Loop and Logging System (CLI + Image Upload Interface)"""

import threading
import csv
from datetime import datetime
stop_flag = threading.Event()

def save_log(user_input, language, task, result, filename="medassist_log.csv"):
    """Logs the interaction to a CSV file."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = [timestamp, user_input, language, task, result]

    try:
        with open(filename, 'a', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            # Write header if file is empty
            if f.tell() == 0:
                writer.writerow(["Timestamp", "User Input", "Language", "Task Type", "Response"])
            writer.writerow(log_entry)
        # print(f"Log saved to {filename}") # Optional: uncomment for verbose logging confirmation
    except Exception as e:
        print(f"Error saving log: {e}")

def chat_loop():
    print("="*60)
    print("   Welcome to MedAssist Agent 🏥")
    print("   Type 'quit' or 'exit' to stop")
    print("   Type 'image' to upload a medical image")
    print("="*60)

    while not stop_flag.is_set():
        try:
            user_input = input("\n👤 You: ").strip()
        except (EOFError, KeyboardInterrupt):
            break

        if not user_input:
            continue

        if user_input.lower() in ["quit", "exit", "bye", "stop"]:
            print("\n👋 Goodbye! Stay healthy!")
            stop_flag.set()
            break

        # ── IMAGE MODE ──────────────────────────────────────
        elif user_input.lower() == "image":
            print("\n📁 Enter the image path (or press Enter to upload in Colab):")

            # Colab file upload
            try:
                from google.colab import files
                print("   Opening file picker...")
                uploaded = files.upload()

                if uploaded:
                    image_path = list(uploaded.keys())[0]
                    print(f"   ✅ Uploaded: {image_path}")

                    # Ask follow-up question
                    question = input("   ❓ Any specific question about this image? (Press Enter to skip): ").strip()

                    # Detect language from question if provided
                    language = detect_language(question) if question else "ENGLISH"

                    print("\n" + "="*60)
                    print("🤖 MedAssist Agent Processing...")
                    print("="*60)
                    print(f"🌐 Language detected: {language}")
                    print("🖼️  Running Image Analyzer...")

                    result = analyze_image(image_path, language, question)

                    print("\n📄 RESULT:\n")
                    print(result)
                    print("="*60)

                    # Save to log
                    save_log(f"[IMAGE] {image_path} | Q: {question}", language, "IMAGE", result)

                else:
                    print("   ❌ No file uploaded.")

            except Exception as e:
                print(f"   ❌ Upload failed: {str(e)}")
                print("   💡 Try providing the full path instead, e.g.: /content/report.jpg")

        # ── TEXT MODE ────────────────────────────────────────
        else:
            medassist_agent(user_input)

# Run it
stop_flag.clear()
chat_loop()

"""# Stop Signal Control for MedAssist Chat Loop"""

# ▶️ Run THIS cell whenever you want to force-stop the agent
stop_flag.set()
print("🛑 Agent stopped. You can now run other cells.")

"""# PubMed Research Integration for Literature-Based Medical Answers"""

import requests
import xml.etree.ElementTree as ET

def search_pubmed(query, max_results=3):
    """Search PubMed and return paper titles + abstracts"""
    try:
        # Step 1: Search for IDs
        search_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
        search_params = {
            "db": "pubmed",
            "term": query,
            "retmax": max_results,
            "retmode": "json"
        }
        search_resp = requests.get(search_url, params=search_params, timeout=10)
        ids = search_resp.json()["esearchresult"]["idlist"]

        if not ids:
            return "No PubMed articles found for this query."

        # Step 2: Fetch details
        fetch_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
        fetch_params = {
            "db": "pubmed",
            "id": ",".join(ids),
            "retmode": "xml"
        }
        fetch_resp = requests.get(fetch_url, params=fetch_params, timeout=10)
        root = ET.fromstring(fetch_resp.content)

        papers = []
        for article in root.findall(".//PubmedArticle"):
            title = article.findtext(".//ArticleTitle", "No title")
            abstract = article.findtext(".//AbstractText", "No abstract available")
            year = article.findtext(".//PubDate/Year", "Unknown year")
            papers.append(f"📄 [{year}] {title}\n   {abstract[:300]}...")

        return "\n\n".join(papers)

    except Exception as e:
        return f"PubMed search failed: {str(e)}"


# Update literature_analyzer to use REAL PubMed
def literature_analyzer(user_input, language):
    print("   🔍 Searching PubMed for real research...")
    pubmed_results = search_pubmed(user_input)

    if language == "URDU":
        system = "آپ ایک طبی معاون ہیں۔ طبی سوالوں کے جواب سادہ اردو میں دیں۔"
        prompt = f"""اس طبی موضوع پر PubMed سے یہ تحقیق ملی ہے:

{pubmed_results}

صارف کا سوال: {user_input}

ان نتائج کو آسان اردو میں سمجھائیں۔"""
    else:
        system = "You are a medical research assistant. Summarize PubMed research clearly."
        prompt = f"""The user asked: {user_input}

Real PubMed research found:
{pubmed_results}

Structure your answer as:
- Key Findings (3-4 bullet points from the papers above)
- What This Means For You (simple explanation)
- Key Takeaways (numbered list)
- Source: Summarized from PubMed research"""

    return generate(prompt, system)

"""# CSV Logging System for MedAssist Interaction History"""

import csv
import os
from datetime import datetime

LOG_FILE = "medassist_log.csv"

def init_log():
    if not os.path.exists(LOG_FILE):
        with open(LOG_FILE, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["timestamp", "user_input", "language", "task_type", "result"])

def save_log(user_input, language, task_type, result):
    with open(LOG_FILE, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            user_input,
            language,
            task_type,
            result[:500]  # save first 500 chars
        ])

def view_log():
    if not os.path.exists(LOG_FILE):
        print("No log yet.")
        return
    with open(LOG_FILE, "r", encoding="utf-8") as f:
        reader = csv.reader(f)
        for row in reader:
            print(row)

init_log()
print("✅ CSV logging ready →", LOG_FILE)

